version: '3.8'

networks:
  frontend:
    external: true

services:
  syslog_mongo:
    image: mongo:7.0
    container_name: syslog_mongodb
    hostname: mongodb
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
    networks:
      - frontend

  syslog_opensearch:
    image: opensearchproject/opensearch:2.19.0
    container_name: syslog_opensearch
    hostname: opensearch
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.disabled=true"
      - "DISABLE_SECURITY_PLUGIN=${DISABLE_SECURITY_PLUGIN}"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
    volumes:
      - /mnt/prod3/graylog_opensearch:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - frontend
    restart: unless-stopped

  syslog_graylog:
    image: graylog/graylog:7.0
    container_name: syslog_graylog
    hostname: graylog
    user: "1100:1100"
    depends_on:
      - syslog_opensearch
      - syslog_mongo
    env_file: .env  # This automatically loads all GRAYLOG_ variables
    volumes:
      - ./graylog_data:/usr/share/graylog/data
    networks:
      - frontend
    restart: always
    ports:
      - "9010:9010/tcp"
      - "1514:1514/tcp"
      - "1514:1514/udp"
      - "1515:1515/udp"