networks:
  frontend:
    external: true

services:
  syslog_mongo:
    image: mongo:7.0
    container_name: syslog_mongodb
    hostname: mongodb
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ./mongo_data:/data/db
    networks:
      - frontend

  syslog_opensearch:
    image: opensearchproject/opensearch:2.19.0
    container_name: syslog_opensearch
    hostname: opensearch
    env_file: .env
    environment:
      - TZ=${TZ}
      - "bootstrap.memory_lock=${OPENSEARCH_BOOTSTRAP_MEMORY_LOCK}"
      - "discovery.type=${OPENSEARCH_DISCOVERY_TYPE}"
      - "action.auto_create_index=${OPENSEARCH_ACTION_AUTO_CREATE_INDEX}"
      - "DISABLE_SECURITY_PLUGIN=${OPENSEARCH_DISABLE_SECURITY_PLUGIN}"
    ports:
      - 9200:9200/tcp  
    networks:
      - frontend      

  syslog_graylog:
    image: graylog/graylog:7.0
    container_name: syslog_graylog
    hostname: graylog
    user: "1100:1100"
    depends_on:
      - syslog_opensearch
      - syslog_mongo
    env_file: .env
    environment:
      - TZ=${TZ}
    volumes:
      - ./graylog_data:/usr/share/graylog/data
    networks:
      - frontend
    restart: always
    ports:
      - "9000:9000/tcp"   # Graylog Web Interface & REST API
      - "1514:1514/tcp"   # Syslog TCP
      - "1514:1514/udp"   # Syslog UDP
      - "514:514/tcp"     # Standard Syslog TCP
      - "514:514/udp"     # Standard Syslog UDP
      - "1515:1515/udp"   # Custom Input