version: '3.8'

networks:
  frontend:
    external: true

services:
  syslog_mongo:
    image: mongo:7.0
    container_name: syslog_mongodb
    hostname: mongodb
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
    networks:
      - frontend

  syslog_opensearch:
    image: opensearchproject/opensearch:2.19.0
    container_name: syslog_opensearch
    hostname: opensearch
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "DISABLE_SECURITY_PLUGIN=true" # Only use this one
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
    ports:
      - 9200:9200/tcp  
    networks:
      - frontend      


  syslog_graylog:
    image: graylog/graylog:7.0
    container_name: syslog_graylog
    hostname: graylog
    user: "1100:1100"
    depends_on:
      - syslog_opensearch
      - syslog_mongo
    env_file: .env
    volumes:
      # ONLY mount the journal to persist logs. 
      # DO NOT mount /usr/share/graylog/data directly.
      - ./graylog_data:/usr/share/graylog/data
    networks:
      - frontend
    restart: always
    ports:
      - "9010:9010/tcp"
      - "1514:1514/tcp"
      - "1514:1514/udp"
      - "1515:1515/udp"